# Generated by Django 4.1.5 on 2023-01-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("permission a", "permission a"),
                            ("permission b", "permission b"),
                        ],
                        max_length=20,
                        verbose_name="permission",
                    ),
                ),
                ("role", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1000)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("F", "FAIBLE"),
                            ("M", "MOYENNE"),
                            ("ELEVEE", "ELEVEE"),
                        ],
                        max_length=15,
                        verbose_name="tag",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("F", "FAIBLE"),
                            ("M", "MOYENNE"),
                            ("ELEVEE", "ELEVEE"),
                        ],
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A faire", "A faire"),
                            ("En cours", "En cours"),
                            ("Terminé", "Terminé"),
                        ],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("B", "back-end"),
                            ("F", "front-end"),
                            ("IOS", "iOS"),
                            ("A", "Android"),
                        ],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
            ],
        ),
    ]
