# Generated by Django 4.1.5 on 2023-01-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[("B", "BUG"), ("A", "AMELIORATION"), ("T", "TACHE")],
                max_length=15,
                verbose_name="tag",
            ),
        ),
    ]
