# Generated by Django 4.1.5 on 2023-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_alter_issue_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="permission",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="permission"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[
                    ("FAIBLE", "FAIBLE"),
                    ("MOYENNE", "MOYENNE"),
                    ("ELEVEE", "ELEVEE"),
                ],
                max_length=10,
                verbose_name="priority",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[
                    ("BUG", "BUG"),
                    ("AMELIORATION", "AMELIORATION"),
                    ("TACHE", "TACHE"),
                ],
                max_length=15,
                verbose_name="tag",
            ),
        ),
    ]
